name: placement_student
version: 0.2.0+2
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  
  # Firebase & Push Notifications
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  
  # Animations & UI Enhancements
  animate_do: ^3.3.4
  lottie: ^3.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  animations: ^2.0.11

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.webp
    - logo.png
    - unilogo.jpg
